### ISSUE TITLE
Support noise values for distances

### ISSUE THREAD

**Issue by viveleroi** [kchapelier/poisson-disk-sampling#1]
I'm looking at implementing poisson disk sampling but using noise values for distances, as described under "Applications" in this article: http://devmag.org.za/2009/05/03/poisson-disk-sampling/

I need that type of distribution for a project. This project seems the most mature so I figured I'd file it as an issue.

**Comment by kchapelier** [comment]
I remember trying to implement it but I encountered some performance issues. The goal should be not to make the currently supported case ("flat" / uniform sampling) significantly slower.

**Comment by viveleroi** [comment]
If you can push whatever work you have I may have some time to help troubleshoot and run profiling. I need some sort of object distribution method similar to this and so far with my research this seems like the best choice.

**Comment by kchapelier** [comment]
I did not keep it but I quickly rewrote it (see [customDistanceFunction branch](https://github.com/kchapelier/poisson-disk-sampling/tree/customDistanceFunction)) but as stated in the commit message, it's very rough and mostly broken although it may give satisfactory results when all the options hit the sweet spot.

Don't loose your time profiling it. As stated in the article you linked the whole grid structure should be changed in ways that would be incompatible with the current use case. The best way to go about it would be to swap the entire implementation using composition if a distanceFunction is provided, or just provide a new constructor altogether. I probably won't have to work on this until a few weeks though. 

The `eyeball.js` from the customDistanceFunction branch should create the following png image :
![test](https://cloud.githubusercontent.com/assets/5741699/21577534/4a15c1f0-cf5e-11e6-9b63-580c5676c8d6.png)

**Comment by kchapelier** [comment]
(also I'd rather have some mocha/chai test suits before properly working on this)

**Comment by viveleroi** [comment]
I appreciate any effort you have/can put in. I'll eventually pull down the branch and see what contribution I might be able to make. The article's png is a good representation of my end goal, I'll be using this to manage 2d terrain decoration for a game and this method is the best candidate I've found and has been recommended to me by several developers.

**Comment by DavisMiculis** [comment]
Hello! I've found this Poisson library to be the best one out! As I stumbled upon same article mentioned, I also wondered, for a functionality like this, for my JS game, this would make great addition!

**Comment by kchapelier** [comment]
@DavisMiculis Thanks for your input on this. This is definitely a feature I'd like to implement, but I personally probably won't have time to work on this before a few months. Sorry about this.

**Comment by DavisMiculis** [comment]
@kchapelier That's ok, I'm currently using previously mentioned customDistanceFunction branch and it seems to be working fine for my needs and I'm currently not that worried about performance.

**Comment by kchapelier** [comment]
This feature has finally been implemented in the 2.0.0 version now available on NPM. Only took 3 years...
