### ISSUE TITLE
Problem with setting rng

### ISSUE THREAD

**Issue by anbello** [kchapelier/poisson-disk-sampling#15]
Hi, thanks for useful library, I am trying to set a different RNG but without success, this is what I do

```
var pds = new PoissonDiskSampling({
    shape: [3*detX, 2*detY],
    minDistance: 25,
    maxDistance: 300,
    tries: 20,
    distanceFunction: function (p) {
        return getMaskValue(p[0], p[1]); // value between 0 and 1
    },
    rng: fxrand()
});
points = pds.fill();
```

Where am i wrong?

**Comment by kchapelier** [comment]
Hello,

The rng option expects a "function to use as random number generator", what you're setting it to here is the result of said function. Removing the parentheses should do the trick. `rng: fxrand`

**Comment by anbello** [comment]
Hello,

I tried with `rng: fxrand` but same problem, even if I have a fixed seed for the RNG I obtain different results at each run.

**Comment by kchapelier** [comment]
Ha, yes. Of course. The rng is not supposed to be passed in the option object (see the documentation). The correct code would be

```js
var pds = new PoissonDiskSampling({
    shape: [3*detX, 2*detY],
    minDistance: 25,
    maxDistance: 300,
    tries: 20,
    distanceFunction: function (p) {
        return getMaskValue(p[0], p[1]); // value between 0 and 1
    }
}, fxrand);
points = pds.fill();
```

**Comment by anbello** [comment]
OK, now works, thanks a lot.
