### ISSUE TITLE
How to exclude transparent pixels on images?

### ISSUE THREAD

**Issue by Wayne5202** [kchapelier/poisson-disk-sampling#9]
How to exclude transparent pixels on images?  It converts the transparent pixels to black.  Not what is expected.

![heightmap](https://user-images.githubusercontent.com/5783243/87865765-f7c50780-c946-11ea-94db-d759b25ca32a.png)

![Capture](https://user-images.githubusercontent.com/5783243/87865908-c3eae180-c948-11ea-9238-476b21608bfe.PNG)

**Comment by kchapelier** [comment]
This library doesn't directly support masking of any sort. You should exclude them in a post-process pass.

Here is an (untested) example of such a process assuming `points` contains the array of points and `imageData` contains the [ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) as retrieved in the _distance-function-with-images-in-browser_ example found in this repository.

```js
var alphaThreshold = 0; // value between 0 and 255

points = points.filter(function (point) {
    // get the index of the alpha pixel value for the given coordinates (point)
    var pixelAlphaIndex = (Math.round(point[0]) + Math.round(point[1]) * imageData.width) * 4 + 3;

    // exclude all points for which the alpha channel value is below the threshold
    return imageData.data[pixelAlphaIndex] > alphaThreshold;
});
```

You might also want to finetune your `distanceFunction` (and your `bias` parameter) to avoid generating so many points in the transparent area. As you've guessed, in the image you're using the transparent pixels are probably encoded as rgb(0,0,0,0) "black but transparent", so your distance function returns 0 which generates this dense set of dots.

**Comment by Wayne5202** [comment]
Thank you! Works perfect as written.

![Capture2](https://user-images.githubusercontent.com/5783243/87882225-b2e3b400-c9cc-11ea-9b47-31fe32441afb.PNG)
